#!/usr/bin/env bash
# Print Best School 10 times and say hi on the 9 iteration
# Set initial counter
i="1"

# Use a while loop to iterate 10 times
while [ $i -le "10" ]; do
    # Check if it's the 9th iteration
    if [ "$i" -eq "9" ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi

    # Increment the counter
    ((i++))
done
